apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eksctl-admin
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - pods
  - services
  - secrets
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksctl-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eksctl-admin
subjects:
- kind: User
  name: arn:aws:sts::142980311878:assumed-role/eksworkshop-admin/i-093e62db8773bbd28
  apiGroup: rbac.authorization.k8s.io
